# Generated by Django 5.2.9 on 2025-12-08 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Public_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('occupation', models.CharField(blank=True, max_length=150, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('district', models.CharField(blank=True, choices=[('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Madurai', 'Madurai'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Salem', 'Salem'), ('Erode', 'Erode'), ('Tirunelveli', 'Tirunelveli'), ('Vellore', 'Vellore'), ('Thoothukudi', 'Thoothukudi'), ('Dindigul', 'Dindigul'), ('Thanjavur', 'Thanjavur'), ('Kanyakumari', 'Kanyakumari'), ('Namakkal', 'Namakkal'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Villupuram', 'Villupuram'), ('Cuddalore', 'Cuddalore'), ('Ramanathapuram', 'Ramanathapuram'), ('Sivagangai', 'Sivagangai'), ('Nagapattinam', 'Nagapattinam'), ('Perambalur', 'Perambalur'), ('Ariyalur', 'Ariyalur'), ('Tiruvarur', 'Tiruvarur'), ('Tirupur', 'Tirupur')], max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
