# Generated by Django 5.2.9 on 2025-12-11 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0003_usersurveysession_usersurveyanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersurveyanswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='administator.usersurveysession'),
        ),
    ]
