# Generated by Django 5.2.9 on 2025-12-12 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administator', '0004_alter_usersurveyanswer_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='survey_reports/')),
                ('survey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='administator.survey')),
            ],
        ),
    ]
