# administator/signals.py

from django.db.models.signals import post_save
from django.dispatch import receiver
import json, openai, re
from collections import Counter

from .models import UserSurveySession, SurveyReport, Survey, SurveyResponse, SurveyQuestion,UserSurveyAnswer
from .views import render_report_html
from .pdf_utils import html_to_pdf_bytes

client = openai.OpenAI(api_key="")

def call_openai_for_html(prompt):
    try:
        resp = client.chat.completions.create(
            model="gpt-4.1-mini",
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=2000,
        )
        return resp.choices[0].message.content
    except Exception as e:
        print("❌ OpenAI Error:", e)
        return None


# ---------------------------------------
# Helper: check if all sessions are completed
# ---------------------------------------
def all_sessions_completed(survey: Survey) -> bool:
    qs = survey.user_survey_sessions.all()
    if not qs.exists():
        return False
    return not qs.filter(is_completed=False).exists()


# ---------------------------------------
# Build aggregated survey data for AI
# ---------------------------------------
def build_survey_data(survey: Survey):
    sessions = UserSurveySession.objects.filter(survey=survey, is_completed=True)
    total_participants = sessions.count()

    # Collect all answers across sessions
    all_answers = UserSurveyAnswer.objects.filter(session__in=sessions)
    answer_texts = [a.answer_text.strip() for a in all_answers if a.answer_text]

    # Aggregate simple word/frequency counts for visualization
    word_counter = Counter()
    for text in answer_texts:
        words = text.split()
        word_counter.update(words)

    return {
        "survey": {
            "id": survey.id,
            "title": survey.title,
            "total_participants": total_participants,
            "total_answers": len(answer_texts)
        },
        "answers": answer_texts,
        "word_frequencies": dict(word_counter.most_common(20))  # top 20 frequent words
    }


# ---------------------------------------
# Fallback HTML generator if AI fails
# ---------------------------------------
def create_professional_html(survey, data):
    total = data["survey"]["total_participants"]
    total_answers = data["survey"]["total_answers"]

    # Top words for basic visualization
    labels = list(data["word_frequencies"].keys())
    values = list(data["word_frequencies"].values())

    html = f"""<!doctype html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Survey Report - {survey.title}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <style>
    body{{font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Arial; padding:20px; color:#222}}
    .header{{display:flex;justify-content:space-between;align-items:center;gap:20px}}
    .title{{font-size:28px;margin:0}}
    .meta{{color:#666}}
    .card{{background:#fff;border-radius:8px;box-shadow:0 4px 12px rgba(15,15,15,0.06);margin:18px 0;padding:18px}}
    footer{{margin-top:24px;color:#888;font-size:13px}}
  </style>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
</head>
<body>
  <div class="header">
    <div>
      <h1 class="title">{survey.title}</h1>
      <div class="meta">Participants: <strong>{total}</strong></div>
    </div>
    <div class="meta">Generated by SurveyLens</div>
  </div>

  <div class="card">
    <h2>Executive Summary</h2>
    <p>This report summarizes <strong>{total_answers}</strong> answers from <strong>{total}</strong> participants. The visualizations highlight the most common trends and key insights.</p>
  </div>

  <div class="card">
    <h2>Top Keywords / Word Frequency</h2>
    <canvas id="wordChart" width="600" height="300"></canvas>
  </div>

  <div class="card">
    <h2>Recommendations</h2>
    <ul>
      <li>Focus on frequently mentioned topics for improvements.</li>
      <li>Consider areas with contradictory feedback.</li>
      <li>Use survey insights for decision making and planning.</li>
    </ul>
  </div>

  <footer>Report generated automatically.</footer>

  <script>
    const ctx = document.getElementById('wordChart');
    if(ctx){{
      new Chart(ctx.getContext('2d'), {{
        type: 'bar',
        data: {{
          labels: {json.dumps(labels)},
          datasets: [{{
            label: 'Word Frequency',
            data: {json.dumps(values)},
            backgroundColor: 'rgba(54, 162, 235, 0.6)',
            borderColor: 'rgba(54, 162, 235, 1)',
            borderWidth: 1
          }}]
        }},
        options: {{
          responsive: true,
          plugins: {{
            legend: {{display:false}},
            title: {{display:true,text:'Top 20 Word Frequencies'}}
          }}
        }}
      }});
    }}
  </script>
</body>
</html>"""
    return html


# ---------------------------------------
# Utility: strip markdown fences from AI output
# ---------------------------------------
def strip_markdown_fences(text):
    text = text.strip()
    m = re.search(r"^```(?:html|text|)?\s*(.*?)\s*```$", text, re.DOTALL | re.IGNORECASE)
    if m:
        return m.group(1).strip()
    return text


# ---------------------------------------
# MAIN SIGNAL: generate AI-powered survey report
# ---------------------------------------
@receiver(post_save, sender=UserSurveySession)
def auto_generate_report(sender, instance, created, **kwargs):
    survey = instance.survey

    if not instance.is_completed:
        return
    if SurveyReport.objects.filter(survey=survey).exists():
        return
    if not all_sessions_completed(survey):
        return

    print("🚀 Generating AI-powered survey report…")

    data = build_survey_data(survey)

    if data["survey"]["total_participants"] == 0:
        print("⚠ No participants, skipping.")
        return

    prompt = f"""
You are a senior data analyst. Generate a professional, print-ready HTML survey report.

Requirements:
- Include survey title, total participants, and total answers.
- Provide executive summary (2-4 sentences).
- Include key insights, advantages, disadvantages.
- Include recommendations for decision making.
- Include at least one visualization using Chart.js (bar, pie, or donut).
- Use actual survey answers and aggregated data (word frequency or trends).
- Return ONLY HTML (no markdown, no JSON, self-contained with inline CSS and JS).

DATA:
{json.dumps(data, ensure_ascii=False)}
"""

    raw_html = call_openai_for_html(prompt)
    html = None
    if raw_html:
        candidate = raw_html.strip()
        if candidate.startswith("<") and ("<html" in candidate.lower() or "<body" in candidate.lower()):
            html = candidate
        else:
            html = strip_markdown_fences(candidate)
            if not html.startswith("<"):
                print("⚠ AI returned invalid HTML, using fallback")
                html = create_professional_html(survey, data)
    else:
        print("⚠ AI unavailable, using fallback")
        html = create_professional_html(survey, data)

    # Generate PDF
    try:
        pdf_bytes = html_to_pdf_bytes(html)
    except Exception as e:
        print("⚠ PDF generation failed:", e)
        pdf_bytes = None

    report_obj, _ = SurveyReport.objects.get_or_create(survey=survey)
    report_obj.data_json = data
    report_obj.html_content = html

    if pdf_bytes:
        from django.core.files.base import ContentFile
        filename = f"survey_{survey.id}_report.pdf"
        report_obj.pdf_file.save(filename, ContentFile(pdf_bytes), save=False)

    report_obj.save()
    print("🎉 Survey report generated:", report_obj.id)
